version: 0.1.{build}
image: Visual Studio 2017
configuration: Debug
platform: Any CPU
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}-preview'
  package_version: '{version}-preview'
  assembly_version: '{version}-preview'
  file_version: '{version}'
  informational_version: '{version}-preview'
nuget:
  disable_publish_on_pr: true
before_build:
- cmd: nuget sources add -name "myget.org" -source "https://www.myget.org/F/winnster/api/v3/index.json"
- cmd: nuget restore
build:
  verbosity: minimal
artifacts:
- path: src\AutomationFoundation\bin\$(configuration)\AutomationFoundation.*.nupkg
  name: NuGet Package