version: 0.1.{build}
image: Visual Studio 2019
configuration: Release
platform: Any CPU

skip_branch_with_pr: true

environment:
  sonarcloud_token:
    secure: WSZCNtuf3h9M4BxNiFQ7SQPwGkg3+LqSMZRyfYruiicYvc1BzYaN90n8pNEsPAKs
  snk_passphrase: 
    secure: Wl4NefzdMAo7GP7gP11aWDrxKoQPC0eN78TZFcZBbHGMW3geBDFu40RVF1GxTFUaFzN/lAcQ3qL9m8huHSWLBg==
  snk_salt:
    secure: tIuRlNokDRTBkah55IRfeATr4WWOEfQOLDqUjrDMMcPEmgq4yOTHzQFKEky67G9rk51D2VvdMFsTcDQrecDonA==
  semver_suffix: preview

init:
  - cmd: nuget sources add -name "myget.org" -source "https://www.myget.org/F/winnster/api/v3/index.json"

install:
  - cmd: choco install secure-file --ignore-checksums
  - cmd: dotnet tool install dotnet-sonarscanner --global

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}-preview'
  package_version: '{version}-preview'
  assembly_version: '{version}-preview'
  file_version: '{version}'
  informational_version: '{version}-preview'

nuget:
  disable_publish_on_pr: true

before_build:
  - cmd: secure-file.exe -decrypt Winnster.snk.enc -secret %snk_passphrase% -salt %snk_salt%
  - cmd: dotnet sonarscanner begin /k:"AutomationFoundation" /v:"%APPVEYOR_BUILD_VERSION%-preview" /d:"sonar.branch.name=%APPVEYOR_REPO_BRANCH%" /d:"sonar.host.url=https://sonarcloud.io" /o:"winnster" /d:"sonar.login=%sonarcloud_token%" /d:"sonar.cs.vstest.reportsPaths=**/*.trx" /d:"sonar.cs.opencover.reportsPaths=**/coverage.opencover.xml" /d:"sonar.exclusions=**\Primitives\**,**\tools\**"
  - cmd: nuget restore

build_script:
  - cmd: dotnet build AutomationFoundation.sln /p:Configuration="%Configuration%" /p:Platform="%Platform%"

test_script:
  - cmd: dotnet test AutomationFoundation.sln /p:Configuration="%Configuration%" /p:Platform="%Platform%" /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=".\TestResults\coverage.opencover.xml" --no-build --logger trx

after_test:
  - cmd: dotnet sonarscanner end /d:"sonar.login=%sonarcloud_token%"

artifacts:
  - path: '**\*.nupkg'
    name: NuGet
  - path: '**\TestResult.xml'
    name: Test Results
  - path: '**\coverage.opencover.xml'
    name: Coverage Results

deploy:
  provider: NuGet
  server: https://www.myget.org/F/winnster/api/v2/package
  api_key:
    secure: j1UnxyPBIzKNE91vJAVHOdoAumEAruRWZYres7ahOLY99HcGHtztXDu+ckZ6g6Mr
  skip_symbols: true
  artifact: /.*\.nupkg/
  on:
    branch: master