version: 0.1.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU

skip_branch_with_pr: true

environment:
  sonarcloud_token:
    secure: WSZCNtuf3h9M4BxNiFQ7SQPwGkg3+LqSMZRyfYruiicYvc1BzYaN90n8pNEsPAKs
  snk_passphrase: 
    secure: Wl4NefzdMAo7GP7gP11aWDrxKoQPC0eN78TZFcZBbHGMW3geBDFu40RVF1GxTFUaFzN/lAcQ3qL9m8huHSWLBg==
  snk_salt:
    secure: tIuRlNokDRTBkah55IRfeATr4WWOEfQOLDqUjrDMMcPEmgq4yOTHzQFKEky67G9rk51D2VvdMFsTcDQrecDonA==

init:
  - cmd: nuget sources add -name "myget.org" -source "https://www.myget.org/F/winnster/api/v3/index.json"
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  - cmd: choco install opencover
  - cmd: choco install sonarscanner-msbuild-net46
  - ps: set-alias opencover "${env:LocalAppData}\Apps\OpenCover\OpenCover.Console.exe"
  - ps: set-alias securefile ".\appveyor-tools\secure-file.exe"
  - ps: iex ((New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/appveyor/secure-file/master/install.ps1'))

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}-preview'
  package_version: '{version}-preview'
  assembly_version: '{version}-preview'
  file_version: '{version}'
  informational_version: '{version}-preview'

nuget:
  disable_publish_on_pr: true

before_build:
  - cmd: appveyor-tools\secure-file.exe -decrypt Winnster.snk.enc -secret %snk_passphrase% -salt %snk_salt%
  - cmd: SonarScanner.MSBuild.exe begin /k:"AutomationFoundation" /v:"%APPVEYOR_BUILD_VERSION%-preview" /d:"sonar.host.url=https://sonarcloud.io" /o:"winnster" /d:"sonar.login=%sonarcloud_token%" /d:"sonar.cs.nunit.reportsPaths=**/TestResult.xml" /d:"sonar.cs.opencover.reportsPaths=**/opencover.xml"
  - cmd: nuget restore

build:
  verbosity: minimal

test_script:
  - ps: opencover -target:"C:\Tools\NUnit3\nunit3-console.exe" -targetargs:"$(get-childitem *.tests.dll -recurse | where { $_.FullName -notmatch 'obj' } | %{ `"$_`" }) --skipnontestassemblies" -register -output:opencover.xml

after_test:
  - cmd: SonarScanner.MSBuild.exe end /d:"sonar.login=%sonarcloud_token%"

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

artifacts:
  - path: '**\*.nupkg'
    name: NuGet
  - path: '**\TestResult.xml'
    name: Test Results
  - path: '**\opencover.xml'
    name: Coverage Results
