name: CI

on: [ push, pull_request ]

env:
  VERSION: 0.2.0
  CONFIGURATION: Release

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 15

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Decrypt SNK file
      run: ./.github/scripts/decrypt_snk.bat
      env:
        snk_passphrase: ${{ secrets.SNK_PASSPHRASE }}

    - uses: benjlevesque/short-sha@v1.2
      id: short-sha
      
    - name: Run build
      run: dotnet build --configuration ${{ env.CONFIGURATION }} /p:Version="${{ env.VERSION }}${{ env.VERSION_SUFFIX }}"
      env:
        VERSION_SUFFIX: -preview-${{ steps.short-sha.outputs.sha }}

    - name: Run test
      run: dotnet test --configuration ${{ env.CONFIGURATION }} --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: nuget-packages
        path: |
          **/*.nupkg

  publish:
    runs-on: ubuntu-latest
    needs: build

    if: github.ref == 'refs/heads/main'

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: nuget-packages
    
    - name: Publish packages
      run: dotnet nuget push **/*.nupkg -k ${NUGET_TOKEN} -s ${PUBLISH_URL} --skip-duplicate --no-symbols
      env:
        NUGET_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_URL: https://nuget.pkg.github.com/automationfoundation/index.json
