name: CI

on: [ push, pull_request ]

env:
  VERSION: 0.2.0
  CONFIGURATION: Release

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 15

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0

    - name: Install Java JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Decrypt SNK file
      run: ./.github/scripts/decrypt_snk.bat
      env:
        snk_passphrase: ${{ secrets.SNK_PASSPHRASE }}

    - uses: benjlevesque/short-sha@v1.2
      id: short-sha

    - name: Install SonarScanner for MSBuild
      run: dotnet tool install --global dotnet-sonarscanner

    - name: Prepare analysis with SonarScanner  
      run: dotnet-sonarscanner begin /k:"${{ vars.SONAR_PROJECT_KEY }}" /o:"${{ vars.SONAR_ORGANIZATION }}" /d:sonar.host.url="${{ vars.SONAR_URL }}" /d:sonar.analysis.configuration="${{ env.CONFIGURATION }}"  /d:sonar.sources="src" /d:sonar.tests="test" /d:"sonar.cs.nunit.reportsPaths=test/**/TestResult.xml" /d:"sonar.cs.opencover.reportsPaths=test/**/*.opencover.xml"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      
    - name: Run build
      run: dotnet build --configuration ${{ env.CONFIGURATION }} /p:Version="${{ env.VERSION }}${{ env.VERSION_SUFFIX }}"
      env:
        VERSION_SUFFIX: -preview-${{ steps.short-sha.outputs.sha }}

    - name: Run tests
      run: dotnet test --configuration ${{ env.CONFIGURATION }} --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

    - name: End analysis with SonarScanner
      run: dotnet-sonarscanner end
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: nuget-packages
        path: |
          **/*.nupkg

  publish:
    runs-on: ubuntu-latest
    needs: build

    if: github.ref == 'refs/heads/main'

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: nuget-packages
    
    - name: Publish packages
      run: dotnet nuget push **/*.nupkg -k ${NUGET_TOKEN} -s ${PUBLISH_URL} --skip-duplicate --no-symbols
      env:
        NUGET_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_URL: https://nuget.pkg.github.com/automationfoundation/index.json
